#!/usr/bin/env python3
"""Wiki Builder: content/*/**.md -> static/en,ko/**.html

Stdlib only. Parses YAML frontmatter, converts Markdown to semantic HTML, and
wraps every page in the shared site template (assets/style.css + header/footer).

index.html is hand-curated and is NOT regenerated by this script; only the
<style> block is kept in sync with assets/style.css.
"""

import glob
import html
import os
import re
import sys

CWD = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT_DIR = os.path.join(CWD, "content")
PUBLIC = {"en": os.path.join(CWD, "static", "en"), "ko": os.path.join(CWD, "static", "ko")}
ASSETS = os.path.join(CWD, "assets")

LANGS = {"en": "en", "ko": "ko"}
STRINGS = {
    "en": {
        "lang": "en",
        "subtitle": "Seminar-level documentation of papers, concepts, and guides.",
        "source": "Source",
        "authors": "Authors",
        "arxiv": "arXiv",
        "published": "Published",
        "back": "← Back to Index",
        "portal": "Wiki Portal",
        "other": "Also available in Korean",
        "toc": "Contents",
        "portal_short": "Wiki",
        "nav_recent": "Recent",
        "nav_categories": "Categories",
        "nav_sources": "Sources",
        "footer": "Verified against the original source.",
        "switch": "Read this page in Korean",
        "switch_missing": "No Korean version of this page yet — open the Korean portal",
    },
    "ko": {
        "lang": "ko",
        "subtitle": "논문, 개념, 가이드에 대한 세미나 수준 문서.",
        "source": "출처",
        "authors": "저자",
        "arxiv": "arXiv",
        "published": "발행일",
        "back": "← 인덱스로 돌아가기",
        "portal": "위키 포털",
        "other": "한국어 버전도 있습니다",
        "toc": "목차",
        "portal_short": "위키",
        "nav_recent": "최근 글",
        "nav_categories": "카테고리",
        "nav_sources": "출처",
        "footer": "원문 대조 검증 완료.",
        "switch": "이 문서를 영어로 읽기",
        "switch_missing": "이 문서의 영어 버전이 아직 없습니다 — 영어 포털로 이동",
    },
}


# Files that are hand-curated at the output path and must never be generated.
# content/<lang>/index.md would otherwise overwrite static/<lang>/index.html.
SKIP_NAMES = {"index.md"}

# Quartz build leftovers: served by the old pipeline, reference hashed bundles
# that no longer exist. Not regenerated; removed so they stop 404-ing.
STALE_OUTPUTS = ["404.html", "concepts/index.html"]

# Generated pages that are authored by hand and must never be pruned.
HAND_WRITTEN_OUTPUTS = {"index.html"}


# --------------------------------------------------------------------------
# frontmatter
# --------------------------------------------------------------------------
def parse_frontmatter(text):
    """Return (meta_dict, body). Handles the simple scalar/list YAML used here."""
    meta = {}
    if not text.startswith("---"):
        return meta, text
    end = text.find("\n---", 3)
    if end == -1:
        return meta, text
    block = text[3:end]
    rest = text[end + 4 :]
    rest = rest.lstrip("\n")

    for line in block.split("\n"):
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            items = [v.strip().strip("'\"") for v in val[1:-1].split(",")]
            meta[key] = [v for v in items if v]
        else:
            meta[key] = val.strip("'\"")

    # Some files repeat a bare `key: value` line right after the closing ---.
    # Drop leading body lines that are still frontmatter-shaped.
    lines = rest.split("\n")
    while lines and re.match(r"^[A-Za-z_][\w-]*:\s*(\S.*)?$", lines[0]) and not lines[0].startswith("#"):
        lines.pop(0)
    return meta, "\n".join(lines).lstrip("\n")


# --------------------------------------------------------------------------
# markdown -> html
# --------------------------------------------------------------------------
INLINE_CODE = re.compile(r"`([^`]+)`")
BOLD = re.compile(r"\*\*([^*]+)\*\*")
ITALIC = re.compile(r"(?<![*\w])\*([^*\n]+)\*(?!\*)")
LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")


def escape(text):
    return html.escape(text, quote=False)


def inline(text):
    """Escape, then apply inline markdown. Code spans are extracted first so
    their contents are never treated as markup."""
    spans = []

    def stash(match):
        spans.append(f"<code>{escape(match.group(1))}</code>")
        return f"\x00{len(spans) - 1}\x00"

    text = INLINE_CODE.sub(stash, text)
    text = escape(text)

    def link_sub(match):
        label, href = match.group(1), match.group(2)
        attrs = ""
        if href.startswith("http"):
            attrs = ' target="_blank" rel="noopener"'
        return f'<a href="{html.escape(href, quote=True)}"{attrs}>{label}</a>'

    text = LINK.sub(link_sub, text)
    text = BOLD.sub(r"<strong>\1</strong>", text)
    text = ITALIC.sub(r"<em>\1</em>", text)

    for i, span in enumerate(spans):
        text = text.replace(f"\x00{i}\x00", span)
    return text


def _lang_of(rel_path):
    """Map a repo-relative content path such as content/ko/sources/x.md to
    (lang, path-within-lang). Returns (None, rel_path) if not under content/."""
    parts = rel_path.split("/")
    if len(parts) >= 2 and parts[0] == "content" and parts[1] in ("en", "ko"):
        return parts[1], "/".join(parts[2:])
    return None, rel_path


def _candidates(md_rel_path, href, lang):
    """Yield plausible repo-relative interpretations of href, best first.

    Content files use several relative-link conventions inconsistently:
    relative to their own file (../../ko/...), relative to the language root
    (sources/...), or relative to the repo root (content/ko/...). normpath
    against the file's directory mangles the latter two into nonexistent
    paths, so try each convention and let the filesystem decide.
    """
    src_dir = os.path.dirname(md_rel_path)
    lang_dir = os.path.dirname(f"content/{lang}/x")  # content/<lang>
    seen = set()
    for base in (src_dir, lang_dir, "content", "."):
        cand = os.path.normpath(os.path.join(base, href)).replace(os.sep, "/")
        if cand not in seen:
            seen.add(cand)
            yield cand


def rewrite_md_links(body, md_rel_path, lang):
    """Convert .md links to .html under /<lang>/ served paths.

    Cross-language links appear in several forms: markdown links to
    ../ko/<path>.md, bare language switches like /ko/concepts/x or
    /wiki/ko/x, and content/ko/<path>.md. All must resolve to the sibling
    language's page under the served site root, i.e. /<other>/..., so
    the link works both on disk and in the browser. Same-language absolute
    links (/en/...) are normalised to /en/... too.
    """
    other = "ko" if lang == "en" else "en"
    prefix = f"../{other}/"

    def sub(match):
        label, href = match.group(1), match.group(2)
        if href.startswith(("http", "#", "mailto:")):
            return match.group(0)
        # An unresolved templating token is a content gap, not a real target.
        # Emit the label as plain text rather than a link that 404s.
        if "PLACEHOLDER" in href or href.startswith("[") or href.startswith("{{"):
            return label
        if href.startswith(prefix):
            rest = href[len(prefix) :][: -len(".md")]
            return f"[{label}](/{other}/{rest}.html)"
        # /ko/... or legacy /wiki/ko/... -> sibling language root
        for lead in (f"/{other}/", f"/wiki/{other}/"):
            if href.startswith(lead):
                rest = href[len(lead) :]
                if rest.endswith(".md"):
                    rest = rest[: -len(".md")]
                return f"[{label}](/{other}/{rest}.html)"
        # /en/... or legacy /wiki/en/... -> this language's root
        for lead in (f"/{lang}/", f"/wiki/{lang}/"):
            if href.startswith(lead):
                rest = href[len(lead) :]
                if rest.endswith(".md"):
                    rest = rest[: -len(".md")]
                return f"[{label}](/{lang}/{rest}.html)"
        if not href.endswith(".md"):
            return match.group(0)
        for cand in _candidates(md_rel_path, href, lang):
            cand_lang, cand_rest = _lang_of(cand)
            if cand_lang is None:
                continue
            # test the SOURCE file, not the emitted html, so link resolution
            # does not depend on build ordering
            if not os.path.exists(os.path.join("content", cand_lang, cand_rest)):
                continue
            return f"[{label}](/{cand_lang}/{cand_rest[: -len('.md')]}.html)"
        # unresolved by convention: fall back to a unique basename match in
        # the content tree (handles links with a miscounted number of ../)
        for l in (lang, other):
            hits = glob.glob(
                os.path.join("content", l, "**", os.path.basename(href)), recursive=True
            )
            if len(hits) == 1:
                cand_lang, cand_rest = _lang_of(hits[0].replace(os.sep, "/"))
                if cand_lang:
                    return f"[{label}](/{cand_lang}/{cand_rest[: -len('.md')]}.html)"
        # genuinely unresolvable: leave the original markup untouched
        return match.group(0)

    return LINK.sub(sub, body)


# A line that is nothing but a cross-language "other version" pointer, e.g.
# `[English version](../../../../en/....md)` or `> 한국어: [한국어 버전](/ko/...)`.
# The header switch now covers language switching (and points at the live
# counterpart instead of a possibly renamed target), so these redundant lines
# are dropped. Only standalone lines match: an inline reference inside real
# prose is left alone.
_VERSION_LABEL = re.compile(
    r"^(?:english(?:\s+versions?)?|korean(?:\s+versions?)?|한국어(?:\s*버전)?)\s*$",
    re.IGNORECASE,
)
_VERSION_PREFIX = re.compile(
    r"^(?:english|korean|한국어)(?:\s+versions?)?\s*:\s*$", re.IGNORECASE
)
_VERSION_LINK = re.compile(r"^(.*?)\[([^\]]*)\]\(([^)]*)\)\s*$")
_VERSION_WORD = re.compile(r"versions?|버전", re.IGNORECASE)


def _is_version_link_line(line, lang):
    other = "ko" if lang == "en" else "en"
    s = line.strip()
    if s.startswith(">"):
        s = s[1:].strip()
    m = _VERSION_LINK.match(s)
    if not m:
        return False
    prefix = m.group(1).strip()
    # A leading flag emoji or similar marker is decoration, not content.
    label = re.sub(r"^[^\w\s]+", "", m.group(2)).strip()
    href = m.group(3).strip()
    if _VERSION_LABEL.match(label):
        if not prefix:
            # A bare "[English](...)"-style line is only a version pointer
            # when it says "version" outright or targets the other language.
            return bool(_VERSION_WORD.search(label)
                        or f"/{other}/" in href or f"/{other}/" in label)
        return bool(_VERSION_PREFIX.match(prefix))
    # Link text is something else (e.g. a bare URL as the label) but the
    # line is introduced as a version pointer to the other language.
    if _VERSION_PREFIX.match(prefix):
        target = href + " " + label
        return f"/{other}/" in target or f"/wiki/{other}/" in target
    return False


def strip_version_links(body, lang):
    """Drop standalone other-language version-pointer lines from a body."""
    return "\n".join(
        line for line in body.split("\n") if not _is_version_link_line(line, lang)
    )


def markdown_to_html(body, md_rel_path, lang):
    out = []
    lines = body.split("\n")
    i = 0
    n = len(lines)
    in_list = None

    def close_list():
        nonlocal in_list
        if in_list:
            out.append(f"</{in_list}>")
            in_list = None

    while i < n:
        line = lines[i]
        stripped = line.strip()

        # fenced code
        if stripped.startswith("```"):
            close_list()
            i += 1
            buf = []
            while i < n and not lines[i].strip().startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1
            out.append("<pre><code>" + escape("\n".join(buf)) + "</code></pre>")
            continue

        if not stripped:
            close_list()
            i += 1
            continue

        # horizontal rule
        if re.match(r"^([-*_])\1{2,}$", stripped):
            close_list()
            out.append("<hr />")
            i += 1
            continue

        # heading
        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            close_list()
            depth = len(m.group(1))
            # The page <h1> comes from frontmatter, so a leading "# Title" in
            # the body would duplicate it. Emit it as <h2> here and let
            # build_lang strip that first one; deeper levels map straight
            # across (## -> h2, ### -> h3) so section styling applies.
            level = max(depth, 2)
            out.append(f"<h{level}>{inline(m.group(2).strip())}</h{level}>")
            i += 1
            continue

        # blockquote
        if stripped.startswith(">"):
            close_list()
            buf = []
            while i < n and lines[i].strip().startswith(">"):
                buf.append(lines[i].strip().lstrip(">").strip())
                i += 1
            out.append(f"<blockquote><p>{inline(' '.join(buf))}</p></blockquote>")
            continue

        # table
        if "|" in stripped and i + 1 < n and re.match(r"^\|?[\s:|-]+\|[\s:|-]+$", lines[i + 1].strip()):
            close_list()
            header = [c.strip() for c in stripped.strip("|").split("|")]
            i += 2
            rows = []
            while i < n and "|" in lines[i] and lines[i].strip():
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            out.append('<table class="md-table">')
            out.append("<thead><tr>" + "".join(f"<th>{inline(c)}</th>" for c in header) + "</tr></thead><tbody>")
            for row in rows:
                out.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in row) + "</tr>")
            out.append("</tbody></table>")
            continue

        # lists
        m_ul = re.match(r"^[-*+]\s+(.*)$", stripped)
        m_ol = re.match(r"^\d+[.)]\s+(.*)$", stripped)
        if m_ul or m_ol:
            want = "ul" if m_ul else "ol"
            if in_list != want:
                close_list()
                out.append(f"<{want}>")
                in_list = want
            out.append(f"<li>{inline((m_ul or m_ol).group(1))}</li>")
            i += 1
            continue

        # paragraph
        close_list()
        buf = [stripped]
        i += 1
        while i < n and lines[i].strip() and not re.match(
            r"^(#{1,6}\s|[-*+]\s|\d+[.)]\s|>|```|[-*_]{3,}$)", lines[i].strip()
        ):
            buf.append(lines[i].strip())
            i += 1
        out.append(f"<p>{inline(' '.join(buf))}</p>")

    close_list()
    return "\n".join(out)


# --------------------------------------------------------------------------
# template
# --------------------------------------------------------------------------
def depth_to_root(rel_path):
    return "../" * (len(rel_path.split("/")) - 1)


def render_page(title, meta, body_html, lang, rel_path, toc_html="",
                other_href=None, other_has_page=True):
    s = STRINGS[lang]
    root = depth_to_root(rel_path)
    other = "ko" if lang == "en" else "en"
    # The header switch points at the same document in the other language so
    # readers stay in context. Without a counterpart it falls back to the
    # other portal (visually dimmed, title says so) instead of 404-ing.
    if other_href is None:
        other_href = f"/{other}/index.html"
        other_has_page = False
    switch_class = "lang-switch" + ("" if other_has_page else " is-fallback")
    switch_title = s["switch"] if other_has_page else s["switch_missing"]
    other_label = other.upper()

    meta_bits = []
    if meta.get("authors"):
        authors = meta["authors"]
        authors = ", ".join(authors) if isinstance(authors, list) else str(authors)
        meta_bits.append(
            f'<p class="doc-meta"><span class="label">{s["authors"]}</span> {escape(authors)}</p>'
        )
    pub = meta.get("published") or meta.get("published_date")
    if pub and str(pub).lower() not in ("true", "false"):
        meta_bits.append(
            f'<p class="doc-meta"><span class="label">{s["published"]}</span> {escape(str(pub))}</p>'
        )
    if meta.get("arxiv_id"):
        arxiv = escape(str(meta["arxiv_id"]))
        link = meta.get("url") or f"https://arxiv.org/abs/{arxiv}"
        meta_bits.append(
            f'<p class="doc-meta"><span class="label">{s["arxiv"]}</span> '
            f'<a href="{html.escape(str(link), quote=True)}" target="_blank" rel="noopener">{arxiv}</a></p>'
        )
    meta_html = "\n".join(meta_bits)

    toc_block = f'<nav class="toc"><p class="toc-title">{s["toc"]}</p>{toc_html}</nav>' if toc_html else ""

    return f"""<!DOCTYPE html>
<html lang="{s['lang']}" dir="ltr">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="{escape(title)}" />
<title>{escape(title)} — {s['portal']}</title>
<link rel="stylesheet" href="{root}assets/style.css" />
</head>
<body class="doc">
<header class="site-header">
  <div class="wrap header-inner">
    <a class="brand" href="{root}index.html">{s['portal_short']}</a>
    <nav class="header-nav">
      <a href="{root}index.html#recent">{s['nav_recent']}</a>
      <a href="{root}index.html#categories">{s['nav_categories']}</a>
      <a href="{root}index.html#sources">{s['nav_sources']}</a>
    </nav>
    <a class="{switch_class}" href="{other_href}" hreflang="{other}" title="{escape(switch_title)}">{other_label}</a>
  </div>
</header>

<div class="wrap">
  <article class="doc-body">
    <header class="doc-header">
      <h1>{escape(title)}</h1>
      <p class="subtitle">{s['subtitle']}</p>
      {meta_html}
    </header>
    {toc_block}
    <div class="prose">
{body_html}
    </div>
    <p class="back-link"><a href="{root}index.html">{s['back']}</a></p>
  </article>
</div>

<footer class="site-footer">
  <div class="wrap">
    <p>{s['footer']}</p>
  </div>
</footer>
</body>
</html>
"""


# --------------------------------------------------------------------------
# build
# --------------------------------------------------------------------------
def collect_toc(body_html):
    """Small TOC built from the h2 headings already rendered."""
    items = re.findall(r'<h2 id="[^"]*">(.*?)</h2>', body_html)
    if not items:
        return ""
    parts = ["<ul>"]
    for inner in items:
        label = re.sub(r"<[^>]+>", "", inner)
        parts.append(f'<li><a href="#sec-{slug(label)}">{label}</a></li>')
    parts.append("</ul>")
    return "\n".join(parts)


def slug(text):
    """URL-safe anchor id.

    Must preserve non-ASCII: Korean and other CJK headings previously
    collapsed to an empty string, so every such heading got id="sec-" and the
    table of contents linked nowhere. Percent-encoding belongs to the URL
    layer, not to the id itself.
    """
    text = str(text).lower()
    # Keep word characters (including Hangul/CJK) and spaces; treat the rest
    # as separators.
    text = re.sub(r"[^\w\s-]", " ", text, flags=re.UNICODE)
    text = re.sub(r"[\s_]+", "-", text.strip())
    return re.sub(r"-{2,}", "-", text).strip("-") or "section"


def add_anchors(body_html):
    """Give each h2/h3 a stable, unique id so the TOC can link to it."""
    seen = {}

    def sub(match):
        level, inner = match.group(1), match.group(2)
        label = re.sub(r"<[^>]+>", "", inner)
        base_slug = slug(label)
        # Repeated headings ("Background" twice, "References" in both
        # languages) would otherwise collapse onto one id.
        count = seen.get(base_slug, 0)
        seen[base_slug] = count + 1
        anchor = base_slug if count == 0 else f"{base_slug}-{count + 1}"
        return f'<h{level} id="sec-{anchor}">{inner}</h{level}>'

    return re.sub(r"<h([23])>(.*?)</h\1>", sub, body_html)


def build_css():
    """Write static/<lang>/assets/style.css and deploy portal.js.

    Both live in scripts/ as the single source of truth (site_css.py and
    portal.js); edit them there rather than in the generated output.
    A missing portal.js is a build error, not a silent skip: without it
    every filter, sort and pagination control on the portal is dead.
    """
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from site_css import SHARED, DOC

    css = SHARED.rstrip() + "\n\n" + DOC.lstrip() + "\n"

    portal_src = os.path.join(os.path.dirname(os.path.abspath(__file__)), "portal.js")
    if not os.path.exists(portal_src):
        raise SystemExit(f"missing {portal_src} — portal interactivity would ship broken")
    with open(portal_src, "rb") as fh:
        portal_bytes = fh.read()
    for lang, pub in PUBLIC.items():
        target_dir = os.path.join(pub, "assets")
        os.makedirs(target_dir, exist_ok=True)
        with open(os.path.join(target_dir, "portal.js"), "wb") as out:
            out.write(portal_bytes)
        print(f"  deployed assets/portal.js into static/{lang}/")

    written = []
    for lang, pub in PUBLIC.items():
        target_dir = os.path.join(pub, "assets")
        os.makedirs(target_dir, exist_ok=True)
        css_path = os.path.join(target_dir, "style.css")
        with open(css_path, "w", encoding="utf-8") as f:
            f.write(css)
        written.append(css_path)
    return written


def build_lang(lang):
    src_root = os.path.join(CONTENT_DIR, lang)
    out_root = PUBLIC[lang]
    if not os.path.isdir(src_root):
        print(f"!! no content/{lang} directory, skipping", file=sys.stderr)
        return 0

    written = 0
    for dirpath, _dirnames, filenames in os.walk(src_root):
        for name in sorted(filenames):
            if not name.endswith(".md") or name in SKIP_NAMES:
                continue
            src = os.path.join(dirpath, name)
            rel = os.path.relpath(src, src_root).replace(os.sep, "/")
            with open(src, "r", encoding="utf-8", errors="replace") as f:
                raw = f.read()

            meta, body = parse_frontmatter(raw)
            body = rewrite_md_links(body, rel, lang)
            body = strip_version_links(body, lang)
            body_html = markdown_to_html(body, rel, lang)
            body_html = add_anchors(body_html)
            # The body's leading "# <title>" duplicates the <h1> in the header.
            body_html = re.sub(
                r'^<h2 id="[^"]*">.*?</h2>\s*', "", body_html, count=1, flags=re.S
            )

            title = meta.get("title") or re.sub(r"[_-]+", " ", name[:-3]).strip()
            if not title:
                m = re.search(r"^#\s+(.*)$", body, re.M)
                title = m.group(1).strip() if m else name[:-3]

            out_rel = rel[:-3] + ".html"
            out_path = os.path.join(out_root, out_rel)
            os.makedirs(os.path.dirname(out_path), exist_ok=True)
            toc = collect_toc(body_html)
            # Header language switch: same document in the other language when
            # its source exists, otherwise the other portal as fallback.
            other = "ko" if lang == "en" else "en"
            if os.path.isfile(os.path.join(CONTENT_DIR, other, rel)):
                other_href = f"/{other}/{out_rel}"
                other_has_page = True
            else:
                other_href = f"/{other}/index.html"
                other_has_page = False
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(render_page(title, meta, body_html, lang, out_rel, toc,
                                    other_href, other_has_page))
            written += 1

    print(f"  {lang}: wrote {written} pages")
    return written


def prune_orphans(lang):
    """Delete generated .html files with no corresponding source .md.

    Renaming or removing a source file otherwise leaves a stale page behind:
    it stays in the output tree and gets linked from nothing, which is how
    duplicate/renamed article directories accumulated orphans.
    """
    src_root = os.path.join(CONTENT_DIR, lang)
    out_root = PUBLIC[lang]
    expected = set()
    for dirpath, _dirs, files in os.walk(src_root):
        for name in files:
            if not name.endswith(".md") or name in SKIP_NAMES:
                continue
            rel = os.path.relpath(os.path.join(dirpath, name), src_root)
            expected.add(rel[:-3] + ".html")

    removed = 0
    for dirpath, _dirs, files in os.walk(out_root):
        for name in files:
            if not name.endswith(".html"):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, out_root)
            if rel in expected:
                continue
            if name in HAND_WRITTEN_OUTPUTS:
                continue
            os.remove(full)
            removed += 1
    return removed


def main():
    print("Build: content -> static/en / static/ko")
    css_paths = build_css()
    for path in css_paths:
        print(f"  wrote {os.path.relpath(path, CWD)}")
    total = sum(build_lang(lang) for lang in LANGS)
    for lang, pub in PUBLIC.items():
        for name in STALE_OUTPUTS:
            stale = os.path.join(pub, name)
            if os.path.exists(stale):
                os.remove(stale)
                print(f"  removed stale {os.path.relpath(stale, CWD)}")
        removed = prune_orphans(lang)
        if removed:
            print(f"  pruned {removed} orphaned page(s) from static/{lang}/")
    print(f"Build completed: {total} pages across {len(LANGS)} languages")
    if total == 0:
        raise SystemExit("no pages written — content directories are empty")

    # Guard: a source file that produced no page is a silent failure. This
    # previously shipped a builder with no entry point, which wrote nothing
    # and still exited 0, so the cron reported success on a no-op.
    # A stub is a placeholder for an unwritten article. Rendering it is fine,
    # but the build must never be the thing that quietly lets one ship: the
    # original RSS failure was 40 empty files published as if they were real.
    pending = []
    for lang in LANGS:
        src_root = os.path.join(CONTENT_DIR, lang)
        for dirpath, _dirs, files in os.walk(src_root):
            for fname in files:
                if not fname.endswith(".md"):
                    continue
                full = os.path.join(dirpath, fname)
                try:
                    with open(full, encoding="utf-8", errors="replace") as fh:
                        head = fh.read(3000)
                except OSError:
                    continue
                if "status: pending" in head or "[Content pending]" in head:
                    pending.append(os.path.relpath(full, CWD))
    if pending:
        print(
            f"  NOTE: {len(pending)} article(s) are still stubs "
            f"([Content pending]) and render as placeholders",
            file=sys.stderr,
        )
        for path in sorted(pending)[:5]:
            print(f"        {path}", file=sys.stderr)
        if len(pending) > 5:
            print(f"        ... and {len(pending) - 5} more", file=sys.stderr)

    for lang in LANGS:
        src_root = os.path.join(CONTENT_DIR, lang)
        sources = [
            name
            for _dp, _dn, fnames in os.walk(src_root)
            for name in fnames
            if name.endswith(".md") and name not in SKIP_NAMES
        ]
        built = sum(
            1
            for _dp, _dn, fnames in os.walk(PUBLIC[lang])
            for _f in fnames
            if _f.endswith(".html") and _f not in HAND_WRITTEN_OUTPUTS
        )
        if built < len(sources):
            print(
                f"  WARNING: {len(sources)} source .md but {built} .html under "
                f"static/{lang}/ ({len(sources) - built} unbuilt)",
                file=sys.stderr,
            )
            if built == 0:
                raise SystemExit(f"static/{lang} has no generated pages — build did not run")
    print("Build verified: page counts match source counts")


if __name__ == "__main__":
    main()